### ISSUE TITLE
[RFE] Nicer explanations for failure

### ISSUE THREAD

**Issue by djberg96** [openshift-online/ocm-api-metamodel#134]
I'm trying to port over one of our apps, and I figured I'd start small. So, I created a `root_resource.model`, `applications_resource.model` and an `application_type.model` file. They're mostly a copy pasta of some of the other models I saw in the ocm-api-model project.

I've got a local clone of the ocm-sdk-go project, and I'm running the following command on my Mac:

`make model_version=HEAD model_url=/Users/dberger/Dev/ocm-api-model generate`

This results in the following:

```
E: Resource 'Application' isn't completely defined
E: Can't read model: there was 1 error
```

I would like a more helpful error message here, something that explains to me exactly what I'm missing, because it's not immediately obvious to me.

BTW, current fork is here if you have any insights:

https://github.com/djberg96/ocm-api-model/tree/status_board

**Comment by djberg96** [comment]
I believe this was addressed at some point.

**Comment by jhernand** [comment]
It is not fixed yet. I am reopening.
