### ISSUE TITLE
Later metamodel releases do not generate ocm-api-model sucessfully

### ISSUE THREAD

**Issue by renan-campos** [openshift-online/ocm-api-metamodel#173]
There appears to be issues generating the ocm-sdk from ocm-api-model using the latest metamodel code:
I built the metamodel using make binary, then went to the ocm-api-model repository and ran:
```
ocm-api-metamodel/metamodel generate go --model=model --base=github.com/openshift-online/ocm-sdk-go --output=./sdk/
```
With the latest metamodel code, the above command fails with the following error:
```
E: Type 'string' isn't completely defined
E: Can't read model: there was 1 error
```
If I move the metamodel code to the version specified in the Makefile of ocm-api-model, v0.0.45, then the model is successfully generated.

Is anyone familiar with what this error means?

**Comment by jhernand** [comment]
I reverted the change that caused that issue. Please try version 0.0.52 of the metamodel and report the results.

**Comment by renan-campos** [comment]
Thank you, I have confirmed that the command above successfully completes for with the new metamodel version 0.0.52.
